### ISSUE TITLE
Alphabetize list of supported types

### ISSUE THREAD

**Issue by r-barnes** [isoverse/isoreader#149]
Please alphabetize the list of supported types in the README to make it easier to determine what is supported (unless there are good reasons for the current organization).

openjournals/joss-reviews/issues/2878

**Comment by sebkopf** [comment]
Good point, kept the grouping the same (file types `continuous flow`, `dual inlet` and `scan`) but put the groups in alphabetical order and the file extensions within each group also in alphabetical order. Moved the `type` column in the first position to clarify the grouping by file type. Update now live on the master branch `README` and at https://isoreader.isoverse.org/
