### ISSUE TITLE
peak detect params

### ISSUE THREAD

**Issue by danote** [isoverse/isoreader#28]
This is not an issue with isoreader, but rather an idea for a new functionality, which you may or may not consider worth the time. I was just thinking that it would be awesome if isoreader allowed the user to re-evaluate a dxf trace with new peak detection parameters. In my experience, changing the peak detection parameters in Isodat can have important effects on delta values, but it is cumbersome to re-evaluate whole datasets in isodat varying peak detect params. If isoreader could evaluate the peaks, it would be easy for the user to test a range of peak detect params and see what results in best data quality. I think a lot of people arbitrarily choose peak detect params just because it is hard to test them. This could help. Just a thought. I know you don't have time to re-write all of Isodat though.

**Comment by sebkopf** [comment]
this would be a great feature! absolutely agree peak detection should be supported for continuous flow files. probably belongs into isoprocessor though --> moved to isoprocessor
